[package]
name = "regex-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.83", features = ["nightly", "span-locations"] }
quote = "1.0.36"
syn = "2.0.65"
